apiVersion: v1
kind: Secret
metadata:
  name: todo-app-secrets
  namespace: todo-app
type: Opaque
data:
  api-url: aHR0cDovL2xvY2FsaG9zdDozMDAx
  jwt-secret: bXktc2VjcmV0LWtleQ==
  database-url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc0Bsb2NhbGhvc3Q6NTQzMi9kYg==
  redis-url: cmVkaXM6Ly9sb2NhbGhvc3Q6NjM3OQ==

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
  namespace: todo-app
data:
  NODE_ENV: "production"
  LOG_LEVEL: "debug"
  REACT_APP_API_URL: "http://todo-app-backend-service:3001"
